name: Build and Package with jpackage

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build fat JAR with Shadow plugin
        run: ./gradlew shadowJar

      - name: Package with jpackage
        run: |
          $ErrorActionPreference = "Stop"

          $JAR_PATH = Get-ChildItem -Recurse -Filter "*-all.jar" | Select-Object -First 1
          $OUTPUT_DIR = "dist"
          $TEMP_PATH = "temp"

          jpackage `
            --type app-image `
            --input "$($JAR_PATH.DirectoryName)" `
            --temp "$TEMP_PATH" `
            --dest "$OUTPUT_DIR" `
            --name "ZvukComDownloader" `
            --main-jar "$($JAR_PATH.Name)" `
            --win-console

      - uses: "marvinpinto/action-automatic-releases@latest"
        name: "Create release with EXE artifact"
        if: ${{ github.event.repository.default_branch == github.ref_name && github.event.pull_request == null }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Build"
          files: |
            dist/*
